name: Hello World Workflow

on:
 push: # Se ejecuta cuando haces un push a cualquier rama
   branches:
     - main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout code
        uses: actions/checkout@v3
      - name: Print a message
        run: echo "Hello, world!"
      
